t <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
t <html><head><meta content="text/html;charset=ISO-8859-15"http-equiv="Content-Type">
t <META http-equiv=Content-Language content=de-de>
t <link rel="stylesheet" type="text/css" href="design_night.css">
t <link rel="alternate stylesheet" type="text/css" title="design_day" href="design_day.css">
t <script type="text/javascript" src="styleswitcher.js"></script>
t <title>SD Card File download</title></head>
t <body style="width:800px;margin:0 auto;">
t <h1 style="text-align: center;">Mount Coordinates</h1><br>
t <h2 align=center><br>SD Card File Download</h2>
t <p><font size="3"><br>Download a file from the SD Card root folder.</font></p>
t <form action=upload.cgi method=POST enctype="multipart/form-data" name=filedownload>
t <p><font face="verdana"><br><br><br>Select a File to download from SD Card:<br></font>
t  <input name="File" type="file" size="50" maxlength="1000">
t </p>
t <p align="center">
t  <input type=button value="Send" OnClick="this.form.submit()">
t </p></form>
# t <form action=download.cgi method=POST enctype="multipart/form-data" name=filedownload>
# t <p><font face="verdana"><br><br><br>Select a File to download from the SD Card:<br></font>
# t  <input name="File" type="file" size="50" maxlength="1000">
# t </p>
# t <p align="center">
# t  <input type=button value="Send" OnClick="this.form.submit()">
# t </p></form>
t <p class="style_switcher">
t <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
t <html><head><meta content="text/html;charset=ISO-8859-1" http-equiv="Content-Type">
t <META http-equiv=Content-Language content=de-de>
t </p>
t </body></html>
. End of script must be closed with a period.
