#=====================================================================================
#  SD card catalog content, dynamically read
#=====================================================================================
i pg_header.inc
t <link rel="stylesheet" type="text/css" href="design_night.css">
t <link rel="alternate stylesheet" type="text/css" title="design_day" href="design_day.css">
t <script type="text/javascript" src="styleswitcher.js"></script>
t <title>Catalogues</title>
t </head>
t <script type="text/javascript">
t function GoTo(object) {
t   parent.Catsel.document.Coform.co.value = object;
t   parent.Catsel.document.Coform.sdo.focus();
t }</script>
t <body><P>
c D T
t </P>
t </body></html>
.
