t <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
t <html><head><meta content="text/html;charset=ISO-8859-1" http-equiv="Content-Type">
t <META http-equiv=Content-Language content=en-us>
t <title>Set Password</title>
t <link rel="stylesheet" type="text/css" href="design_night.css">
t <link rel="alternate stylesheet" type="text/css" title="design_day" href="design_day.css">
t <script type="text/javascript" src="styleswitcher.js"></script>
t </head>
t <body style="width:800px;margin:0 auto;">
t <h2 align=center>Set Password</h2>
t <form action="password.cgi" method="POST">
t <p>Set a new password:</P>
t <p><table border=0 width=750>
t <tr><td>New Password:</td>
t <td><input type="text" name="pw"></td></tr>
t <tr><td>Retype Password:</td>
t <td><input type="text" name="pw2"></td></tr>
t </table>
t <input type="submit" value="Set Password"></P><HR>
t <P><INPUT TYPE=BUTTON VALUE="Home" OnClick="location='/index.htm'">
t <INPUT TYPE=BUTTON VALUE="Refresh" OnClick="location='/password.cgi'">
t </p></form>
t <p class="style_switcher">
t <a href="#" onclick="setActiveStyleSheet('standard'); return false;">Night mode</a> -----
t <a href="#" onclick="setActiveStyleSheet('design_day'); return false;">Day mode</a>
t </p>
t </body></html>
. End of script must be closed with a period.
