t <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
t <html><head><meta content="text/html;charset=ISO-8859-15"http-equiv="Content-Type">
t <META http-equiv=Content-Language content=es-es> 
t <script language=JavaScript type="text/javascript" src="xml_http.js"></script>
t <link rel="stylesheet" type="text/css" href="design_night.css">
t <link rel="alternate stylesheet" type="text/css" title="design_day" href="design_day.css">
t <script type="text/javascript" src="styleswitcher.js"></script>
t <title>Catalogues</title></head>
t <script type="text/javascript">
t function GoTo(object) {
t   parent.Catsel.document.Coform.co.value = object;
t   parent.Catsel.document.Coform.sdo.focus();
t }</script>
t <body><P>
c D T
t </P></body></html>
.
